### ISSUE TITLE
Existing package

### ISSUE THREAD

**Issue by thosakwe** [sh4869/pbsm#1]
Hi, I actually have an existing package for this, perhaps we could collaborate to make it better instead: https://github.com/thosakwe/dart_scripts

**Comment by sh4869** [comment]
This package is highly experimental and I would like to make useful this package more (ex: add version command, publish command, and more).   So until I release 1.0.0, I develop this package.  Thank you for your invitation!

**Comment by thosakwe** [comment]
Ok!
